export const dataProject = [
  {
    id: 1,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2023",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
  {
    id: 2,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2023",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
  {
    id: 3,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2023",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
  {
    id: 4,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2023",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
  {
    id: 5,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2022",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
  {
    id: 6,
    projectName: "The Shawshank Redemption",
    dayStart: "01/01/2022",
    dayEnd: "05/01/2022",
    staff: [
      { name: "Nguyen Van A", position: "Leader" },
      { name: "Nguyen Van B", position: "Member" },
      { name: "Nguyen Van C", position: "Member" },
      { name: "Nguyen Van D", position: "Member" },
      { name: "Nguyen Van E", position: "Member" },
    ],
  },
];
